### ISSUE TITLE
怎么在已有的博客中加入这样的简历页

### ISSUE THREAD

**Issue by nick-zhy** [xaoxuu/hexo-theme-resume#10]
您好， 我已经基于hexo搭建了一个个人博客，我现在想部署一个这样的简历，让我能通过博客进入，应该怎么操作呢？
1. 克隆下来的简历文件应该放在哪个位置？是应该放在博客的文件夹内吗？
2. 这样一个简历页是否也要部署在github。部署地址能否为username.github.io/resume
3. 简历页和博客是否应该分开解析？
4. 如何在博客中加入指向简历的按钮，直接放链接可以吗？

**Comment by xaoxuu** [comment]
1: 单独一个仓库
2: 是的
3: 是的
4: 可以

**Comment by nick-zhy** [comment]
> 1: 单独一个仓库 2: 是的 3: 是的 4: 可以

成功了，谢谢大佬的帮助！
