### ISSUE TITLE
The CNAME `resume.js.org` is already taken.

### ISSUE THREAD

**Issue by nick-zhy** [xaoxuu/hexo-theme-resume#12]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-resume/releases/latest) version of Resume.
- [x] I have reviewed [guidelines for resume](https://resume.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.
我想在已经搭好的博客上应用这个模板。我的操作是这样的，先克隆本项目到本地，然后将repo改成我新建的resume仓库，再hexo d -g到远端。但是这时github给我发邮件提示"The CNAME `resume.js.org` is already taken."，我就想是不是应该把CNAME改成我自己的域名nickzhy.cc，但是改了过后提示"The CNAME `nickzhy.cc` is already taken."，然后我又把CNAME改成nickzhy.cc/resuem，结果又发邮件提示"The CNAME `nickzhy.cc/cv` is not properly formatted. "。请问我该怎么解决这个问题呢？

**Comment by xaoxuu** [comment]
把CNAME删掉

**Comment by nick-zhy** [comment]
是的，成功了，但是必须要把所有CNMAME文件都删掉，而且您这个仓库里面没有放入模板，需要克隆模板进去才能完整使用。但我最后还有一个小问题，就是英文界面没问题了，切换中文就没有页面了，是不是中文页面要单独部署？

**Comment by xaoxuu** [comment]
不用啊，删掉souce里面那个CNAME就行了，生成的页面自然就没有了

**Comment by xaoxuu** [comment]
你直接克隆这个仓库就行了：
https://github.com/xaoxuu/resume-docs
这是个示例，只需要把内容改成自己的。
这样用起来最简单。
