### ISSUE TITLE
material-x主题怎么找不到啦

### ISSUE THREAD

**Issue by MellonGuan** [xaoxuu/hexo-theme-resume#13]
**非常非常想用主题** material-x 这个主题给人的 感受真的好！！！

### 但是访问时404了：https://xaoxuu.com/wiki/material-x/

![image](https://user-images.githubusercontent.com/19337606/98219831-81492580-1f88-11eb-96cb-6f96b651973d.png)

### 求博主释放资源，给你打赏

**Comment by xaoxuu** [comment]
改名为 Volantis 了：
https://github.com/volantis-x/hexo-theme-volantis
在 releases 页面找到旧的版本就是了
