### ISSUE TITLE
material-x主题还有吗

### ISSUE THREAD

**Issue by MellonGuan** [xaoxuu/hexo-theme-resume#14]
**非常非常想用 material-x 主题，给人的感受真的好！！！**

### 这个网址已经找不到了！！！ https://xaoxuu.com/wiki/material-x/

![image](https://user-images.githubusercontent.com/19337606/98220674-9c686500-1f89-11eb-96c2-e47da1e1bff9.png)

### 求博主释放资源，给打赏

**Comment by xaoxuu** [comment]
@MellonGuan  https://volantis.js.org
