### ISSUE TITLE
左侧栏位新增问题

### ISSUE THREAD

**Issue by League2EB** [xaoxuu/hexo-theme-resume#2]
首先谢谢您的贡献
但我尝试寄送邮件给您却没有得到回应，在此跟您留言
主要是想请问如何在同中邮件、电话栏位再新增其他联系方式？
找不到原码写在哪里，还请您协助

https://i.imgur.com/kAOoN00.png

**Comment by xaoxuu** [comment]
https://github.com/xaoxuu/hexo-theme-resume/blob/master/layout/page.ejs
你可以在第10行后面添加代码，也可以等我下次更新

**Comment by League2EB** [comment]
好的谢谢您！

**Comment by xaoxuu** [comment]
已经更新了，现在联系方式是以数组的方式添加的，图标、文字、链接全部自定义。
