### ISSUE TITLE
h2 之间空行是否可调整，pdf 只能靠浏览器打印生成吗

### ISSUE THREAD

**Issue by cuzperf** [xaoxuu/hexo-theme-resume#24]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-resume/releases/latest) version of Resume.
- [x] I have reviewed [guidelines for resume](https://resume.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Describe your question 

1. 想把简历搞成 1 到 2 页，当前 h2 之间的空行太大了，无法做到（尝试修改 css 等，但是未果，可否告知修改的问题，感谢！）
2. pdf 用浏览器打印会有 [gonghs](https://github.com/gonghs) 在其[博客](http://www.ice-maple.com/2020/08/09/%E5%9C%A8%E7%BA%BF%E7%AE%80%E5%8E%86/) 中描述的问题 ，并且给了解决方案：head部分任意编辑一处style块，并加入以下代码
``` css
@media print {
  a[href]:after {
    content: none ;
  }
}
```
实测可解决问题，但不够优雅，能否在此处解决。或者是否有其它生成 pdf 的方式（如果有那第一个问题也不再是问题）。

### Node.js and NPM Information

```
v12.22.12
6.14.16
```

### Package dependencies Information

```
hexo-site@ /home/cuzperf/resume
├── UNMET PEER DEPENDENCY hexo@5.3.0
├── hexo-autonofollow@1.0.1
├── hexo-deployer-git@3.0.0 (github:hexojs/hexo-deployer-git#4f879c56fcbe5b964ddd2083763c94d6d42de860)
├── hexo-lazyload-image@1.0.9
├── hexo-neat@1.0.9
├── hexo-offline@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@3.3.0
├── hexo-renderer-stylus@2.0.1
└── hexo-server@2.0.0

npm ERR! peer dep missing: hexo@^3.2.2, required by hexo-offline@1.0.0
```

### Hexo Configuration

```yml

```

### Resume Configuration

```yml

```

## Other Information 

Edge version: Version 104.0.1293.47 (Official build) (64-bit)

**Comment by cuzperf** [comment]
问题 1 已参考 https://github.com/xaoxuu/hexo-theme-resume/commit/ea945497da39829caea5eed900f25517a8258747 解决

**Comment by cuzperf** [comment]
问题 2 已找到优雅的解决方案。
遗留问题： 能否自动生成 pdf（不依赖于浏览器打印）

**Comment by xaoxuu** [comment]
原本没有考虑直出pdf，因为网站有些东西是不需要打印出来的，例如图片、导航栏、icon等，那个pdf下载按钮是方便自己做好pdf之后给招聘方一键下载用的。

**Comment by cuzperf** [comment]
问题 1 已根据个人喜欢解决：https://github.com/xaoxuu/hexo-theme-resume/compare/main...cuzperf:hexo-theme-resume:layout
问题 2 的解决方案已经提了 PR：https://github.com/xaoxuu/hexo-theme-resume/pull/25

自己上传一个完全不同风格的简历确实也未尝不可
