### ISSUE TITLE
一键部署到阿里云函数计算

### ISSUE THREAD

**Issue by wss-git** [xaoxuu/hexo-theme-resume#28]
你好，这边将您的主题和模版。做成到了一个[开源工具](https://github.com/serverless-devs/serverless-devs)的一个[应用](http://www.devsapp.cn/details.html?name=resume)。也是第一集成个人的主题和模版，不知道有什么产权或者其他问题，这边可以及时哈。如果不行我这边可以及时下架哈 
![image](https://github.com/xaoxuu/hexo-theme-resume/assets/56686088/8aef98dc-69da-4b87-9a26-7ac127215e65)

https://github.com/wss-org/resume-docs

**Comment by xaoxuu** [comment]
随便用哈
