### ISSUE TITLE
支持子目录

### ISSUE THREAD

**Issue by cmpute** [xaoxuu/hexo-theme-resume#3]
目前生成的网站不能部署到子目录（例如xxx.com/yyy/），生成的文件里有几个绝对路径识别的js，能否修改一下使得网页支持`_config.yaml`里面的`root`位置？

**Comment by xaoxuu** [comment]
示例的就是部署到子目录的啊。

> 示例：https://mxclub.github.io/resume
> 示例源码：https://github.com/xaoxuu/resume-example
